version: '2'

services:
  kafka:
    image: spotify/kafka
    ports:
    - 2181:2181
    - 9092:9092

  batch_vur:
    build: .
    image: batch_vur
    shm_size: 256M
    links:
    - kafka
    volumes:
    - ./logs:/logs
    environment:
    - BATCH_VUR_TENANCY_ID=52a36193-7942-4606-a783-15e098f15f0f
    - ZK_ADDR=kafka_1:2181
    ports:
    - 40201/udp
